#!/bin/sh

if [ $# -ne 2 ] ; then
  echo "Usage: `basename $0` <input text file> <output text file>"
  echo "Ensures standard UNIX line endings in output text file"
  exit 0
fi

file=$1
outfile=$2

if [ $file = $outfile ] ; then
  # make a temporary to avoid the original being wiped
  tmpfile=`$FSLDIR/bin/tmpnam`
  cp $file $tmpfile
  origfile=$file
  file=$tmpfile
fi

cat $file | tr -d '\r' > $outfile

if [ X$tmpfile != X ] ; then
    rm $tmpfile
fi
